const usersData = [
  {
    id: 123,
    name: "manucho",
    email: "test@g.com",
    phone_number: "+25476263629",
    country: "KE",
    occupation: "Developer",
    role: "admin",
  },
  {
    id: 121,
    name: "bob",
    email: "test@g.com",
    phone_number: "+25476263629",
    country: "KE",
    occupation: "Developer",
    role: "admin",
  },
  {
    id: 125,
    name: "simon",
    email: "test@g.com",
    phone_number: "+25476263629",
    country: "KE",
    occupation: "Developer",
    role: "admin",
  },
  {
    id: 191,
    name: "amos",
    email: "test@g.com",
    phone_number: "+25476263629",
    country: "KE",
    occupation: "Developer",
    role: "admin",
  },
  {
    id: 191,
    name: "brandon",
    email: "test@g.com",
    phone_number: "+25476263629",
    country: "KE",
    occupation: "Developer",
    role: "admin",
  },
  {
    id: 191,
    name: "elizabeth",
    email: "test@g.com",
    phone_number: "+25476263629",
    country: "KE",
    occupation: "Developer",
    role: "admin",
  },
  {
    id: 191,
    name: "sofia",
    email: "test@g.com",
    phone_number: "+25476263629",
    country: "KE",
    occupation: "Developer",
    role: "admin",
  },
  {
    id: 191,
    name: "jackline",
    email: "test@g.com",
    phone_number: "+25476263629",
    country: "KE",
    occupation: "Developer",
    role: "admin",
  },
  {
    id: 191,
    name: "patrick",
    email: "test@g.com",
    phone_number: "+25476263629",
    country: "KE",
    occupation: "Developer",
    role: "admin",
  },
  {
    id: 191,
    name: "mary",
    email: "test@g.com",
    phone_number: "+25476263629",
    country: "KE",
    occupation: "Developer",
    role: "admin",
  },
];

const products = [
  {
    id: 120,
    userid: 20,
    name: "basket",
    createdat: "test@g.com",
    ofproducts: "+25476263629",
    cost: 230,
  },
  {
    id: 121,
    userid: 21,
    name: "fan",
    createdat: "test@g.com",
    ofproducts: "+25476263629",
    cost: 200,
  },
  {
    id: 122,
    userid: 22,
    name: "shirt",
    createdat: "test@g.com",
    ofproducts: "+25476263629",
    cost: 320,
  },
  {
    id: 12,
    userid: 23,
    name: "ball",
    createdat: "test@g.com",
    ofproducts: "+25476263629",
    cost: 333,
  },
];

export { usersData, products };
